### ISSUE TITLE
Updating a shell app to 1.88.4 causes MFEs that have not yet been updated to error

### ISSUE THREAD

**Issue by erik-inkapool** [seb-oss/green#2328]
### Bug already reported?

- [x] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

`@sebgroup/green-core`

### Description

When updating `@sebgroup/green-core` to 1.88.4 the structure of the global changes from:

<img width="1150" height="215" alt="Image" src="https://github.com/user-attachments/assets/cc0330cb-4aca-418a-be3c-736e692f6abf" />

To:

<img width="1281" height="630" alt="Image" src="https://github.com/user-attachments/assets/6003d7ab-5a4d-4eec-9bb1-8c6c894eb970" />

Loading an older version from a component library or MFE within the page will trigger TypeError containing

```
TypeError: [...].injectGlobalStyles is not a function
```

This seems to be because https://github.com/seb-oss/green/blob/%40sebgroup/green-core%401.88.3/libs/core/src/utils/global-styles.ts#L28 gives back an empty object on the old version.

Doing the reverse thing, i.e. loading 1.88.4 in a component library/MFE on a shell page that is on some version lower than 1.88.4 works but only because the shell page gets there first so initiates the class. Once the 1.88.4 version is run all the functions disappear as can be seen in the screenshots.

I understand this might not be the exact intended use case of the library (multiple versions of green core on the same page), so maybe we need to figure out a better way of doing this. But the exception did surprise us (we've updated green versions out of sync with our MFE for a while and this is the first time we've noted a breaking change like this causing the MFE not to load).

### Steps To Reproduce

A bit difficult to write a simple reproduction step for you for this, but the way this breaks for us is:
1. Shell app using module federation to load it's MFEs with dependency to `@sebgroup/green-core` 1.88.4
2. MFE app with dependency to `@sebgroup/green-core` 1.88.0
3. When the shell app loads the MFE app, `@sebgroup/green-core` tries to call the function `injectGlobalStyles` on an object that only has the version-tagged variant of the GlobalStylesRegistry. The function isn't present, so the MFE throws.

### Current Behaviour

Loading a <1.88.4 version of `@sebgroup/green-core`  once a 1.88.4 version has already loaded throws a type error.

### Expected Behaviour

Loading the <1.88.4 version of `@sebgroup/green-core` should work.

**Comment by erik-inkapool** [comment]
Thanks for the very quick response and release 🚀
